version: '3'
services:
  redis:
    container_name: "${APP_NAME}-redis"
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    container_name: "${APP_NAME}-db"
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    container_name: "${APP_NAME}-app"
    build: .
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/app
      - ./log:/log